name: Worker

on:
  repository_dispatch:
    types: [start]
  workflow_dispatch:
    inputs:
      client:
        description: 'Client ID'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Starting Client
      run: ./client.py ${{ github.event.inputs.client }}
