name: Worker

on:
  repository_dispatch:
    types: [start]
  workflow_dispatch:
    inputs:
      host:
        description: 'hostname'
        required: true
      client:
        description: 'client-id'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Downloading Dependencies
      run: python -m pip install websockets
    - name: Starting Client
      run: python ./client.py ${{ github.event.inputs.host }} ${{ github.event.inputs.client }}
    - name: Keep Alive
      run: ./timeout.ps1
